"""add created_at in animal table

Revision ID: 4ecc24fc848c
Revises: 75b5318b378c
Create Date: 2025-09-02 00:22:33.649219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecc24fc848c'
down_revision: Union[str, Sequence[str], None] = '75b5318b378c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'created_at')
    # ### end Alembic commands ###
